# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02a115ef27958f7c23faaad009bcb46234ee9e3b2ff659bb9fc391cc1b1496d3bcd8b102a1ecb186c90b28eecb15fd2526e35eac73de989a9d102ce210332233

test:
  secret_key_base: 08158ea8e72a0b792b6a18ea78b93462b3112fd438aea56e67b77eff0c28a343ff388595e5b65de33f71b30e81aa4c52cf5857e77e27ec30f792dd45514eb1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
